// #!/usr/bin/env groovy

// // def label = "mypod-${UUID.randomUUID().toString()}"

// // podTemplate(label: label,
// //     namespace: "cje-slaves-digitalhealth-dmz",
// //     containers: [
// //         containerTemplate(name: 'android',
// //                           image: "mingc/android-build-box:latest",
// //                           ttyEnabled: true,
// //                           command: 'cat',
// //                           resourceRequestCpu: '3000m',
// //                           resourceRequestMemory : '10Gi',
// //                           resourceLimitCpu: '3000m',
// //                           resourceLimitMemory: '10Gi')
// //     ]
// // ) {
// //     node(label) {
// //         container('android') {
// //             stage('Git Checkout') {
// //                 checkout scm
// //             }
            
// //             stage('Clean & Compile') {
// //                 script{
// //                         sh "fastlane build_for_screengrab"
// //                 }
// //             }
// //         }  // End of Container - node.
// //     } // End of Node - label
// // } // End of Pod Template

// pipeline {
//     agent {
//         docker { 
//             image 'mingc/android-build-box:latest'
//             args '-u root:sudo'
//             }
//     }
//     stages {
//         stage('Test') {
//             steps {
//                 sh 'fastlane --version'
//             }
//         }
//     }
// }

// pipeline {
//     agent any
//     stages {
//         stage('install node modules...') {
//             agent { 
//                 docker { 
//                         image 'jenkins-docker'
//                     }
//              }
//             steps {
//                 sh 'docker images'
//             }
//         }
//     }
// }

pipeline {
   agent any
//    environment {
//        registry = "magalixcorp/k8scicd"
//        GOCACHE = "/tmp"
//    }
   stages {
       stage('Build') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {
               // Create our project directory.
            //    sh 'cd ${GOPATH}/src'
            //    sh 'mkdir -p ${GOPATH}/src/hello-world'
            //    // Copy all files in our Jenkins workspace to our project directory.               
            //    sh 'cp -r ${WORKSPACE}/* ${GOPATH}/src/hello-world'
               // Build the app.
               sh 'ls -la'              
           }    
       }
    //    stage('Test') {
    //        agent {
    //            docker {
    //                image 'golang'
    //            }
    //        }
    //        steps {                
    //            // Create our project directory.
    //            sh 'cd ${GOPATH}/src'
    //            sh 'mkdir -p ${GOPATH}/src/hello-world'
    //            // Copy all files in our Jenkins workspace to our project directory.               
    //            sh 'cp -r ${WORKSPACE}/* ${GOPATH}/src/hello-world'
    //            // Remove cached test results.
    //            sh 'go clean -cache'
    //            // Run Unit Tests.
    //            sh 'go test ./... -v -short'           
    //        }
    //    }
    //    stage('Publish') {
    //        environment {
    //            registryCredential = 'dockerhub'
    //        }
    //        steps{
    //            script {
    //                def appimage = docker.build registry + ":$BUILD_NUMBER"
    //                docker.withRegistry( '', registryCredential ) {
    //                    appimage.push()
    //                    appimage.push('latest')
    //                }
    //            }
    //        }
    //    }
    //    stage ('Deploy') {
    //        steps {
    //            script{
    //                def image_id = registry + ":$BUILD_NUMBER"
    //                sh "ansible-playbook  playbook.yml --extra-vars \"image_id=${image_id}\""
    //            }
    //        }
    //    }
   }
}
