pipeline {
    agent {
        dockerfile {
            filename 'final/Dockerfile.jenkinsAgent'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
        stages {
        stage('Test') {
            steps {
                sh 'fastlane --version'
            }
        }
    }
}