default_platform(:android)

platform :android do
	desc "Clean"
	lane :clean do
		gradle(
			task: 'clean'
		)
	end

	lane :lint do
		gradle(task: "lint")
	end

	desc "Runs all the tests"
	lane :test do
		gradle(task: "test")
	end

	desc "Build"
	lane :build do
		gradle(task: "clean assembleRelease")
	end
end
